services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user_password
      - POSTGRES_DB=template_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
  
  backend:
    build:
      dockerfile: docker/Dockerfile.backend
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
    env_file: backend/.env
    restart: on-failure:5
    depends_on:
      - db

  frontend:
    build: 
      dockerfile: docker/Dockerfile.frontend
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - "5173:5173"
    restart: on-failure:5
    depends_on:
      - backend

volumes:
  db_data:
    name: db_data
