name: New issue
description: Default issue template
labels: []
body:
  - type: markdown
    attributes:
      value: >
        ## What kind of issue? (Bug, Feature, Docs, ....)

        * [ ] Bug
        * [ ] Feature
        * [ ] Docs

  - type: textarea
    attributes:
      label: Context
      description: Provide additional contenxt about the issue.
    validations:
