name: Code Quality Frontend 
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
  push:
    paths:
      - "src/**"

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm 
        uses: pnpm/action-setup@v4 
      
      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: pnpm install 

      - name: Lint codes
        run: make lint-frontend
