name: Code Quality Backend
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "backend/**"
  push:
    paths:
      - "backend/**"

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --only-dev

      - name: Lint codes
        run: make lint-backend
